/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Objects.Receta;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Eduardo Corrales
 */
public class _12Recetas extends javax.swing.JFrame {

    private int medicoID;
    private int recetaIDSeleccionada = 0;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(_12Recetas.class.getName());

    /**
     * Creates new form Recetas
     */
    public _12Recetas() {
        this.medicoID = medicoID;
        initComponents();
        setLocationRelativeTo(null);

        jRecetas.setRowHeight(25);
        jRecetas.getTableHeader().setReorderingAllowed(false);
        jRecetas.getTableHeader().setFont(new Font("Verdana", Font.PLAIN, 14));
        jRecetas.getTableHeader().setForeground(new Color(102, 153, 0));
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) jRecetas.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);

        cargarRecetas();

        // Botones deshabilitados hasta seleccionar una receta
        jProcesar.setEnabled(false);
        jRechazar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jRecetas = new javax.swing.JTable();
        jProcesar = new javax.swing.JButton();
        jRechazar = new javax.swing.JButton();
        jAtras = new javax.swing.JButton();
        jbarraProsecesar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRecetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Receta", "Descripcion"
            }
        ));
        jRecetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRecetasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jRecetas);

        jProcesar.setText("Procesar");
        jProcesar.addActionListener(this::jProcesarActionPerformed);

        jRechazar.setText("Rechazar");
        jRechazar.addActionListener(this::jRechazarActionPerformed);

        jAtras.setText("< Atras");
        jAtras.addActionListener(this::jAtrasActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProcesar)
                            .addComponent(jRechazar)
                            .addComponent(jbarraProsecesar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jAtras))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAtras)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jProcesar)
                        .addGap(18, 18, 18)
                        .addComponent(jbarraProsecesar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jRechazar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAtrasActionPerformed
        // TODO add your handling code here:
        _11MenuFarmacia menufarmacia = new _11MenuFarmacia(medicoID);

        menufarmacia.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jAtrasActionPerformed
    public void cargarRecetas() {
        jRecetas.setModel(Receta.consultarTodos(this));


        // Ajustar anchos de columnas visibles
        jRecetas.getColumnModel().getColumn(1).setPreferredWidth(150); // PACIENTE
        jRecetas.getColumnModel().getColumn(2).setPreferredWidth(80);  // FECHA
        jRecetas.getColumnModel().getColumn(3).setPreferredWidth(250); // DETALLES
        jRecetas.getColumnModel().getColumn(4).setPreferredWidth(80);  // ESTADO

        // Resetear selección al recargar
        recetaIDSeleccionada = 0;
        jProcesar.setEnabled(false);
        jRechazar.setEnabled(false);
    }

    private void jProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProcesarActionPerformed
        // TODO add your handling code here:
        if (recetaIDSeleccionada == 0) {
            JOptionPane.showMessageDialog(this,
                "Seleccione una receta para procesar.");
            return;
        }

        // Deshabilitar botones durante el proceso
        jProcesar.setEnabled(false);
        jRechazar.setEnabled(false);
        jbarraProsecesar.setValue(0);

        // Hilo secundario para animar la barra sin congelar la UI
        Thread hilo = new Thread(() -> {
            try {
                // Animar barra de 0 a 100
                for (int i = 0; i <= 100; i++) {
                    final int valor = i;
                    javax.swing.SwingUtilities.invokeLater(() ->
                        jbarraProsecesar.setValue(valor));
                    Thread.sleep(30);
                }

                // Eliminar la receta de la BD al terminar la animación
                boolean eliminado = Receta.eliminar(this, recetaIDSeleccionada);

                // Actualizar UI en el hilo de Swing (EDT)
                javax.swing.SwingUtilities.invokeLater(() -> {
                    if (eliminado) {
                        JOptionPane.showMessageDialog(this,
                            "Receta entregada exitosamente.");
                    }
                    jbarraProsecesar.setValue(0);
                    cargarRecetas(); // recargar tabla sin la receta procesada
                });

            } catch (InterruptedException ex) {
                System.out.println("Hilo interrumpido: " + ex.getMessage());
            }
        });
        hilo.start();
    }//GEN-LAST:event_jProcesarActionPerformed

    private void jRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRechazarActionPerformed
        // TODO add your handling code here:
        if (recetaIDSeleccionada == 0) {
            JOptionPane.showMessageDialog(this,
                "Seleccione una receta para rechazar.");
            return;
        }

        // Confirmar antes de rechazar
        int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro que desea rechazar esta receta?",
            "Confirmar rechazo",
            JOptionPane.YES_NO_OPTION
        );
        if (confirmacion != JOptionPane.YES_OPTION) return;

        // Eliminar directamente sin animación
        boolean eliminado = Receta.eliminar(this, recetaIDSeleccionada);
        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Receta rechazada y eliminada.");
            cargarRecetas();
        }
    }//GEN-LAST:event_jRechazarActionPerformed

    private void jRecetasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRecetasMousePressed
        // TODO add your handling code here:
        int fila = jRecetas.getSelectedRow();
        if (fila < 0) return;

        try {
            // Columna 0 oculta contiene el RecetaID
            recetaIDSeleccionada = Integer.parseInt(
                jRecetas.getValueAt(fila, 0).toString());

            // Habilitar botones al seleccionar una receta
            jProcesar.setEnabled(true);
            jRechazar.setEnabled(true);
        } catch (Exception ex) {
            System.out.println("Error al seleccionar receta: " + ex.getMessage());
        }
    }//GEN-LAST:event_jRecetasMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new _12Recetas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAtras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jProcesar;
    private javax.swing.JTable jRecetas;
    private javax.swing.JButton jRechazar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar jbarraProsecesar;
    // End of variables declaration//GEN-END:variables
}
